version: 0.2

phases:
  install:
    commands:
      - sudo apt update
      - sudo apt install nginx -y
  build:
    commands:
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring nginx

artifacts:
  files:
    - '/**/*'
